[versions]
# AGP
agp = "8.6.1"

# Compose
compose-bom = "2025.07.00"
compose-navigation-animation = "2.9.3"
compose-runtime-tracing = "1.8.3"
compose-hilt-navigation = "1.2.0"
compose-coil = "2.7.0"
accompanist = "0.32.0"

# Hilt
hilt = "2.55"

# Database
room = "2.7.2"

# Google
ksp = "2.1.0-1.0.29"

# Java
java-inject = "1"

# Jetpack
appcompat = "1.7.1"
activity-ktx = "1.10.1"
lifecycle = "2.9.2"

# Kotlin
kotlin = "2.1.0"
corutine = "1.8.1"
serialization = "1.7.3"

# Retrofit
retrofit = "3.0.0"
okhttp = "5.1.0"

# Util
moshi-kotlin = "1.15.2"
glide = "4.15.1"
core-ktx = "1.16.0"
core-ktx-version = "1.10.1"
junit = "4.13.2"
junit-version = "1.1.5"
espresso-core = "3.5.1"
material = "1.12.0"


[libraries]
# AGP
agp = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-icon = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "compose-runtime-tracing" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation-animation" }
compose-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-hilt-navigation" }

# Coil
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "compose-coil" }
coil-core = { group = "io.coil-kt", name = "coil", version.ref = "compose-coil" }
coil-gif = { group = "io.coil-kt", name = "coil-gif", version.ref = "compose-coil" }
coil-svg = { group = "io.coil-kt", name = "coil-svg", version.ref = "compose-coil" }

# Accompainst
accompainst-system-ui = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
accompainst-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }

# Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }

# Room
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room"}
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room"}
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}

ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

app-compat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity-ktx" }
lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }

kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
coroutine-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "corutine" }
coroutine-core-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core-jvm", version.ref = "corutine" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
compose-compiler-extension = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-moshi-converter = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

moshi = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx-version" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-version" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

java-inject = { group = "javax.inject", name = "javax.inject", version.ref = "java-inject" }


[bundles]
compose = [
    "compose-ui",
    "compose-tooling",
    "compose-tooling-preview",
    "compose-material3",
    "compose-icon",
    "compose-runtime",
    "compose-runtime-tracing",
    "compose-hilt-navigation"
]

retrofit = [
    "retrofit",
    "retrofit-moshi-converter",
    "okhttp",
    "okhttp-logging-interceptor",
    "moshi"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp"}
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

